package models

// AnnouncementPublishRecord keeps the audit trail for site notice changes.
type AnnouncementPublishRecord struct {
	Model
	OperatorId      int64  `gorm:"not null;index:idx_announcement_record_operator" json:"operatorId" form:"operatorId"`
	PreviousContent string `gorm:"type:text" json:"previousContent" form:"previousContent"`
	Content         string `gorm:"type:text;not null" json:"content" form:"content"`
	Status          string `gorm:"size:32;not null;index:idx_announcement_record_status" json:"status" form:"status"`
	Error           string `gorm:"type:text" json:"error" form:"error"`
	PublishTime     int64  `gorm:"not null;index:idx_announcement_record_publish_time" json:"publishTime" form:"publishTime"`
	CreateTime      int64  `gorm:"not null" json:"createTime" form:"createTime"`
}

// DashboardViewPreference stores named dashboard views per administrator.
type DashboardViewPreference struct {
	Model
	UserId     int64  `gorm:"not null;uniqueIndex:uk_dashboard_view_preference;index:idx_dashboard_view_preference_user" json:"userId" form:"userId"`
	ViewKey    string `gorm:"size:256;not null;uniqueIndex:uk_dashboard_view_preference" json:"viewKey" form:"viewKey"`
	Views      string `gorm:"type:text;not null" json:"views" form:"views"`
	UpdateTime int64  `gorm:"not null" json:"updateTime" form:"updateTime"`
}

const (
	DatabaseBackupRunning = 1
	DatabaseBackupSuccess = 2
	DatabaseBackupFailed  = 3
)

// DatabaseBackup is the durable record for a generated database backup.
// FileName is generated by the service and never comes from an HTTP request.
type DatabaseBackup struct {
	Model
	TriggerType  string `gorm:"size:16;not null;index:idx_database_backup_trigger" json:"triggerType" form:"triggerType"`
	DatabaseType string `gorm:"size:16;not null" json:"databaseType" form:"databaseType"`
	FileName     string `gorm:"size:256;not null;uniqueIndex:uk_database_backup_file" json:"fileName" form:"fileName"`
	Directory    string `gorm:"size:1024;not null" json:"-" form:"-"`
	Status       int    `gorm:"not null;index:idx_database_backup_status" json:"status" form:"status"`
	RequestedBy  int64  `gorm:"not null;default:0;index:idx_database_backup_requested_by" json:"requestedBy" form:"requestedBy"`
	Size         int64  `gorm:"not null;default:0" json:"size" form:"size"`
	Checksum     string `gorm:"size:64" json:"checksum" form:"checksum"`
	Error        string `gorm:"type:text" json:"error" form:"error"`
	StartedAt    int64  `gorm:"not null;default:0" json:"startedAt" form:"startedAt"`
	FinishedAt   int64  `gorm:"not null;default:0" json:"finishedAt" form:"finishedAt"`
	CreateTime   int64  `gorm:"not null;index:idx_database_backup_create_time" json:"createTime" form:"createTime"`
	UpdateTime   int64  `gorm:"not null" json:"updateTime" form:"updateTime"`
}
